/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_pikostudios_muzzle_bridge_Sprite */

#ifndef _Included_dev_pikostudios_muzzle_bridge_Sprite
#define _Included_dev_pikostudios_muzzle_bridge_Sprite
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_pikostudios_muzzle_bridge_Sprite
 * Method:    load
 * Signature: (Ljava/lang/String;)Ldev/pikostudios/muzzle/bridge/Sprite;
 */
JNIEXPORT jobject JNICALL Java_dev_pikostudios_muzzle_bridge_Sprite_load
  (JNIEnv *, jclass, jstring);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Sprite
 * Method:    unload
 * Signature: (Ldev/pikostudios/muzzle/bridge/Sprite;)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Sprite_unload
  (JNIEnv *, jclass, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Sprite
 * Method:    draw
 * Signature: (Ldev/pikostudios/muzzle/bridge/Applet;FFLdev/pikostudios/muzzle/bridge/Tint;)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Sprite_draw
  (JNIEnv *, jobject, jobject, jfloat, jfloat, jobject);

#ifdef __cplusplus
}
#endif
#endif
