/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_pikostudios_muzzle_bridge_ComputePipeline */

#ifndef _Included_dev_pikostudios_muzzle_bridge_ComputePipeline
#define _Included_dev_pikostudios_muzzle_bridge_ComputePipeline
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_pikostudios_muzzle_bridge_ComputePipeline
 * Method:    create
 * Signature: (Ljava/lang/String;ZLdev/pikostudios/muzzle/bridge/Sprite;B)Ldev/pikostudios/muzzle/bridge/ComputePipeline;
 */
JNIEXPORT jobject JNICALL Java_dev_pikostudios_muzzle_bridge_ComputePipeline_create
  (JNIEnv *, jclass, jstring, jboolean, jobject, jbyte);

/*
 * Class:     dev_pikostudios_muzzle_bridge_ComputePipeline
 * Method:    dispatch
 * Signature: (III)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_ComputePipeline_dispatch
  (JNIEnv *, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
