/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_pikostudios_muzzle_bridge_Font */

#ifndef _Included_dev_pikostudios_muzzle_bridge_Font
#define _Included_dev_pikostudios_muzzle_bridge_Font
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_pikostudios_muzzle_bridge_Font
 * Method:    load
 * Signature: (Ldev/pikostudios/muzzle/bridge/Applet;Ljava/lang/String;)Ldev/pikostudios/muzzle/bridge/Font;
 */
JNIEXPORT jobject JNICALL Java_dev_pikostudios_muzzle_bridge_Font_load
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Font
 * Method:    unload
 * Signature: (Ldev/pikostudios/muzzle/bridge/Font;)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Font_unload
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
