/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni_md.h"
#include <jni.h>
/* Header for class dev_pikostudios_muzzle_bridge_SpriteBatch */

#ifndef _Included_dev_pikostudios_muzzle_bridge_SpriteBatch
#define _Included_dev_pikostudios_muzzle_bridge_SpriteBatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_pikostudios_muzzle_bridge_SpriteBatch
 * Method:    load
 * Signature: ([Ljava/lang/String;)Ldev/pikostudios/muzzle/bridge/SpriteBatch;
 */
JNIEXPORT jobject JNICALL Java_dev_pikostudios_muzzle_bridge_SpriteBatch_load
  (JNIEnv *, jclass, jobjectArray);

/*
 * Class:     dev_pikostudios_muzzle_bridge_SpriteBatch
 * Method:    bind
 * Signature: (Ldev/pikostudios/muzzle/bridge/Applet;B)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_SpriteBatch_bind
  (JNIEnv *, jobject, jobject, jbyte);

/*
 * Class:     dev_pikostudios_muzzle_bridge_SpriteBatch
 * Method:    unload
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_SpriteBatch_unload
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
