/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_pikostudios_muzzle_bridge_DirectShader */

#ifndef _Included_dev_pikostudios_muzzle_bridge_DirectShader
#define _Included_dev_pikostudios_muzzle_bridge_DirectShader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_pikostudios_muzzle_bridge_DirectShader
 * Method:    begin
 * Signature: (Ldev/pikostudios/muzzle/bridge/Applet;)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_DirectShader_begin
  (JNIEnv *, jobject, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_DirectShader
 * Method:    end
 * Signature: (Ldev/pikostudios/muzzle/bridge/Applet;)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_DirectShader_end
  (JNIEnv *, jobject, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_DirectShader
 * Method:    create
 * Signature: (Ldev/pikostudios/muzzle/bridge/Shader;I)Ldev/pikostudios/muzzle/bridge/DirectShader;
 */
JNIEXPORT jobject JNICALL Java_dev_pikostudios_muzzle_bridge_DirectShader__1create
  (JNIEnv *, jclass, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
