/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_pikostudios_muzzle_bridge_Joystick */

#ifndef _Included_dev_pikostudios_muzzle_bridge_Joystick
#define _Included_dev_pikostudios_muzzle_bridge_Joystick
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_pikostudios_muzzle_bridge_Joystick
 * Method:    exists
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_dev_pikostudios_muzzle_bridge_Joystick_exists
  (JNIEnv *, jclass, jint);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Joystick
 * Method:    _open
 * Signature: (I)Ldev/pikostudios/muzzle/bridge/Joystick;
 */
JNIEXPORT jobject JNICALL Java_dev_pikostudios_muzzle_bridge_Joystick__1open
  (JNIEnv *, jclass, jint);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Joystick
 * Method:    _queryState
 * Signature: (Ldev/pikostudios/muzzle/bridge/JoystickState;)Z
 */
JNIEXPORT jboolean JNICALL Java_dev_pikostudios_muzzle_bridge_Joystick__1queryState
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
