/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_pikostudios_muzzle_bridge_Shader */

#ifndef _Included_dev_pikostudios_muzzle_bridge_Shader
#define _Included_dev_pikostudios_muzzle_bridge_Shader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_pikostudios_muzzle_bridge_Shader
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Ldev/pikostudios/muzzle/bridge/Shader;
 */
JNIEXPORT jobject JNICALL Java_dev_pikostudios_muzzle_bridge_Shader_create
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Shader
 * Method:    load
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Ldev/pikostudios/muzzle/bridge/Shader;
 */
JNIEXPORT jobject JNICALL Java_dev_pikostudios_muzzle_bridge_Shader_load
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Shader
 * Method:    uploadUniform
 * Signature: (Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Shader_uploadUniform__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Shader
 * Method:    uploadUniform
 * Signature: (Ljava/lang/String;F)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Shader_uploadUniform__Ljava_lang_String_2F
  (JNIEnv *, jobject, jstring, jfloat);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Shader
 * Method:    uploadUniform
 * Signature: (Ljava/lang/String;FF)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Shader_uploadUniform__Ljava_lang_String_2FF
  (JNIEnv *, jobject, jstring, jfloat, jfloat);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Shader
 * Method:    uploadUniform
 * Signature: (Ljava/lang/String;FFF)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Shader_uploadUniform__Ljava_lang_String_2FFF
  (JNIEnv *, jobject, jstring, jfloat, jfloat, jfloat);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Shader
 * Method:    uploadUniform
 * Signature: (Ljava/lang/String;FFFF)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Shader_uploadUniform__Ljava_lang_String_2FFFF
  (JNIEnv *, jobject, jstring, jfloat, jfloat, jfloat, jfloat);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Shader
 * Method:    unload
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Shader_unload
  (JNIEnv *, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Shader
 * Method:    _use
 * Signature: (Ldev/pikostudios/muzzle/bridge/Applet;)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Shader__1use
  (JNIEnv *, jobject, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Shader
 * Method:    _beginShader
 * Signature: (Ldev/pikostudios/muzzle/bridge/Applet;)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Shader__1beginShader
  (JNIEnv *, jobject, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Shader
 * Method:    _endShader
 * Signature: (Ldev/pikostudios/muzzle/bridge/Applet;)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Shader__1endShader
  (JNIEnv *, jobject, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Shader
 * Method:    uploadUniformMat3
 * Signature: (Ljava/lang/String;[F)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Shader_uploadUniformMat3
  (JNIEnv *, jobject, jstring, jfloatArray);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Shader
 * Method:    uploadUniformMat4
 * Signature: (Ljava/lang/String;[F)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Shader_uploadUniformMat4
  (JNIEnv *, jobject, jstring, jfloatArray);

#ifdef __cplusplus
}
#endif
#endif
