/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_pikostudios_muzzle_bridge_ShaderPass */

#ifndef _Included_dev_pikostudios_muzzle_bridge_ShaderPass
#define _Included_dev_pikostudios_muzzle_bridge_ShaderPass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_pikostudios_muzzle_bridge_ShaderPass
 * Method:    create
 * Signature: (Ldev/pikostudios/muzzle/bridge/Shader;)Ldev/pikostudios/muzzle/bridge/ShaderPass;
 */
JNIEXPORT jobject JNICALL Java_dev_pikostudios_muzzle_bridge_ShaderPass_create
  (JNIEnv *, jclass, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_ShaderPass
 * Method:    use
 * Signature: (Ldev/pikostudios/muzzle/bridge/Applet;)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_ShaderPass_use
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
