/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_pikostudios_muzzle_bridge_Mouse */

#ifndef _Included_dev_pikostudios_muzzle_bridge_Mouse
#define _Included_dev_pikostudios_muzzle_bridge_Mouse
#ifdef __cplusplus
extern "C" {
#endif
#undef dev_pikostudios_muzzle_bridge_Mouse_MOUSE_BUTTON_LEFT
#define dev_pikostudios_muzzle_bridge_Mouse_MOUSE_BUTTON_LEFT 0L
#undef dev_pikostudios_muzzle_bridge_Mouse_MOUSE_BUTTON_RIGHT
#define dev_pikostudios_muzzle_bridge_Mouse_MOUSE_BUTTON_RIGHT 1L
#undef dev_pikostudios_muzzle_bridge_Mouse_MOUSE_BUTTON_MIDDLE
#define dev_pikostudios_muzzle_bridge_Mouse_MOUSE_BUTTON_MIDDLE 2L
/*
 * Class:     dev_pikostudios_muzzle_bridge_Mouse
 * Method:    mousePressed
 * Signature: (Ldev/pikostudios/muzzle/bridge/Applet;I)Z
 */
JNIEXPORT jboolean JNICALL Java_dev_pikostudios_muzzle_bridge_Mouse_mousePressed
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Mouse
 * Method:    mouseReleased
 * Signature: (Ldev/pikostudios/muzzle/bridge/Applet;I)Z
 */
JNIEXPORT jboolean JNICALL Java_dev_pikostudios_muzzle_bridge_Mouse_mouseReleased
  (JNIEnv *, jclass, jobject, jint);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Mouse
 * Method:    getMouseX
 * Signature: (Ldev/pikostudios/muzzle/bridge/Applet;)D
 */
JNIEXPORT jdouble JNICALL Java_dev_pikostudios_muzzle_bridge_Mouse_getMouseX
  (JNIEnv *, jclass, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Mouse
 * Method:    getMouseY
 * Signature: (Ldev/pikostudios/muzzle/bridge/Applet;)D
 */
JNIEXPORT jdouble JNICALL Java_dev_pikostudios_muzzle_bridge_Mouse_getMouseY
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
