/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_pikostudios_muzzle_bridge_Sprite */

#ifndef _Included_dev_pikostudios_muzzle_bridge_Sprite
#define _Included_dev_pikostudios_muzzle_bridge_Sprite
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_pikostudios_muzzle_bridge_Sprite
 * Method:    load
 * Signature: (Ljava/lang/String;)Ldev/pikostudios/muzzle/bridge/Sprite;
 */
JNIEXPORT jobject JNICALL Java_dev_pikostudios_muzzle_bridge_Sprite_load
  (JNIEnv *, jclass, jstring);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Sprite
 * Method:    unload
 * Signature: (Ldev/pikostudios/muzzle/bridge/Sprite;)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Sprite_unload
  (JNIEnv *, jclass, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Sprite
 * Method:    create
 * Signature: (IIIIII[B)Ldev/pikostudios/muzzle/bridge/Sprite;
 */
JNIEXPORT jobject JNICALL Java_dev_pikostudios_muzzle_bridge_Sprite_create
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jint, jbyteArray);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Sprite
 * Method:    draw
 * Signature: (Ldev/pikostudios/muzzle/bridge/Applet;FFLdev/pikostudios/muzzle/bridge/Tint;)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Sprite_draw
  (JNIEnv *, jobject, jobject, jfloat, jfloat, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Sprite
 * Method:    drawScaled
 * Signature: (Ldev/pikostudios/muzzle/bridge/Applet;FFFLdev/pikostudios/muzzle/bridge/Tint;)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Sprite_drawScaled
  (JNIEnv *, jobject, jobject, jfloat, jfloat, jfloat, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Sprite
 * Method:    drawResized
 * Signature: (Ldev/pikostudios/muzzle/bridge/Applet;FFIILdev/pikostudios/muzzle/bridge/Tint;)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Sprite_drawResized
  (JNIEnv *, jobject, jobject, jfloat, jfloat, jint, jint, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Sprite
 * Method:    bind
 * Signature: (Ldev/pikostudios/muzzle/bridge/Applet;B)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Sprite_bind
  (JNIEnv *, jobject, jobject, jbyte);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Sprite
 * Method:    getPixels
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_dev_pikostudios_muzzle_bridge_Sprite_getPixels
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
