/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_pikostudios_muzzle_bridge_Shader */

#ifndef _Included_dev_pikostudios_muzzle_bridge_Shader
#define _Included_dev_pikostudios_muzzle_bridge_Shader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_pikostudios_muzzle_bridge_Shader
 * Method:    create
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Ldev/pikostudios/muzzle/bridge/Shader;
 */
JNIEXPORT jobject JNICALL Java_dev_pikostudios_muzzle_bridge_Shader_create
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Shader
 * Method:    load
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)Ldev/pikostudios/muzzle/bridge/Shader;
 */
JNIEXPORT jobject JNICALL Java_dev_pikostudios_muzzle_bridge_Shader_load
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Shader
 * Method:    unload
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Shader_unload
  (JNIEnv *, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Shader
 * Method:    _use
 * Signature: (Ldev/pikostudios/muzzle/bridge/Applet;)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Shader__1use
  (JNIEnv *, jobject, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Shader
 * Method:    _beginShader
 * Signature: (Ldev/pikostudios/muzzle/bridge/Applet;)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Shader__1beginShader
  (JNIEnv *, jobject, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Shader
 * Method:    _endShader
 * Signature: (Ldev/pikostudios/muzzle/bridge/Applet;)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Shader__1endShader
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
