/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_pikostudios_muzzle_bridge_Text */

#ifndef _Included_dev_pikostudios_muzzle_bridge_Text
#define _Included_dev_pikostudios_muzzle_bridge_Text
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_pikostudios_muzzle_bridge_Text
 * Method:    draw
 * Signature: (Ldev/pikostudios/muzzle/bridge/Applet;Ljava/lang/String;FFFLdev/pikostudios/muzzle/bridge/Font;Ldev/pikostudios/muzzle/bridge/Tint;)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Text_draw
  (JNIEnv *, jclass, jobject, jstring, jfloat, jfloat, jfloat, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
