/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_pikostudios_muzzle_bridge_Drawing */

#ifndef _Included_dev_pikostudios_muzzle_bridge_Drawing
#define _Included_dev_pikostudios_muzzle_bridge_Drawing
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_pikostudios_muzzle_bridge_Drawing
 * Method:    startDrawing
 * Signature: (Ldev/pikostudios/muzzle/bridge/Applet;)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Drawing_startDrawing
  (JNIEnv *, jclass, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Drawing
 * Method:    endDrawing
 * Signature: (Ldev/pikostudios/muzzle/bridge/Applet;)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Drawing_endDrawing
  (JNIEnv *, jclass, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Drawing
 * Method:    clearScreen
 * Signature: (Ldev/pikostudios/muzzle/bridge/Tint;)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Drawing_clearScreen
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
