/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_pikostudios_muzzle_bridge_VertexBuffer */

#ifndef _Included_dev_pikostudios_muzzle_bridge_VertexBuffer
#define _Included_dev_pikostudios_muzzle_bridge_VertexBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_pikostudios_muzzle_bridge_VertexBuffer
 * Method:    create
 * Signature: (I[Ldev/pikostudios/muzzle/bridge/VertexBuffer/AttributeDescriptor;)Ldev/pikostudios/muzzle/bridge/VertexBuffer;
 */
JNIEXPORT jobject JNICALL Java_dev_pikostudios_muzzle_bridge_VertexBuffer_create
  (JNIEnv *, jclass, jint, jobjectArray);

/*
 * Class:     dev_pikostudios_muzzle_bridge_VertexBuffer
 * Method:    getSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_dev_pikostudios_muzzle_bridge_VertexBuffer_getSize
  (JNIEnv *, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_VertexBuffer
 * Method:    getStride
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_dev_pikostudios_muzzle_bridge_VertexBuffer_getStride
  (JNIEnv *, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_VertexBuffer
 * Method:    getVAO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dev_pikostudios_muzzle_bridge_VertexBuffer_getVAO
  (JNIEnv *, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_VertexBuffer
 * Method:    getVBO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dev_pikostudios_muzzle_bridge_VertexBuffer_getVBO
  (JNIEnv *, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_VertexBuffer
 * Method:    allocate
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_VertexBuffer_allocate__J
  (JNIEnv *, jobject, jlong);

/*
 * Class:     dev_pikostudios_muzzle_bridge_VertexBuffer
 * Method:    unload
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_VertexBuffer_unload
  (JNIEnv *, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_VertexBuffer
 * Method:    _getTopologyType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dev_pikostudios_muzzle_bridge_VertexBuffer__1getTopologyType
  (JNIEnv *, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_VertexBuffer
 * Method:    allocate
 * Signature: (Ljava/nio/ByteBuffer;J)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_VertexBuffer_allocate__Ljava_nio_ByteBuffer_2J
  (JNIEnv *, jobject, jobject, jlong);

/*
 * Class:     dev_pikostudios_muzzle_bridge_VertexBuffer
 * Method:    write
 * Signature: (Ljava/nio/ByteBuffer;JJ)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_VertexBuffer_write__Ljava_nio_ByteBuffer_2JJ
  (JNIEnv *, jobject, jobject, jlong, jlong);

/*
 * Class:     dev_pikostudios_muzzle_bridge_VertexBuffer
 * Method:    write
 * Signature: ([FJJ)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_VertexBuffer_write___3FJJ
  (JNIEnv *, jobject, jfloatArray, jlong, jlong);

/*
 * Class:     dev_pikostudios_muzzle_bridge_VertexBuffer
 * Method:    write
 * Signature: ([IJJ)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_VertexBuffer_write___3IJJ
  (JNIEnv *, jobject, jintArray, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
