/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_pikostudios_muzzle_bridge_ShaderBuffer */

#ifndef _Included_dev_pikostudios_muzzle_bridge_ShaderBuffer
#define _Included_dev_pikostudios_muzzle_bridge_ShaderBuffer
#ifdef __cplusplus
extern "C" {
#endif
#undef dev_pikostudios_muzzle_bridge_ShaderBuffer_INT_SIZE
#define dev_pikostudios_muzzle_bridge_ShaderBuffer_INT_SIZE 4L
#undef dev_pikostudios_muzzle_bridge_ShaderBuffer_FLOAT_SIZE
#define dev_pikostudios_muzzle_bridge_ShaderBuffer_FLOAT_SIZE 4L
#undef dev_pikostudios_muzzle_bridge_ShaderBuffer_VEC2_SIZE
#define dev_pikostudios_muzzle_bridge_ShaderBuffer_VEC2_SIZE 8L
#undef dev_pikostudios_muzzle_bridge_ShaderBuffer_VEC3_SIZE
#define dev_pikostudios_muzzle_bridge_ShaderBuffer_VEC3_SIZE 12L
#undef dev_pikostudios_muzzle_bridge_ShaderBuffer_VEC4_SIZE
#define dev_pikostudios_muzzle_bridge_ShaderBuffer_VEC4_SIZE 16L
#undef dev_pikostudios_muzzle_bridge_ShaderBuffer_MAT3_SIZE
#define dev_pikostudios_muzzle_bridge_ShaderBuffer_MAT3_SIZE 36L
#undef dev_pikostudios_muzzle_bridge_ShaderBuffer_MAT4_SIZE
#define dev_pikostudios_muzzle_bridge_ShaderBuffer_MAT4_SIZE 64L
/*
 * Class:     dev_pikostudios_muzzle_bridge_ShaderBuffer
 * Method:    create
 * Signature: (ILjava/nio/ByteBuffer;J)Ldev/pikostudios/muzzle/bridge/ShaderBuffer;
 */
JNIEXPORT jobject JNICALL Java_dev_pikostudios_muzzle_bridge_ShaderBuffer_create
  (JNIEnv *, jclass, jint, jobject, jlong);

/*
 * Class:     dev_pikostudios_muzzle_bridge_ShaderBuffer
 * Method:    createEmpty
 * Signature: (I)Ldev/pikostudios/muzzle/bridge/ShaderBuffer;
 */
JNIEXPORT jobject JNICALL Java_dev_pikostudios_muzzle_bridge_ShaderBuffer_createEmpty
  (JNIEnv *, jclass, jint);

/*
 * Class:     dev_pikostudios_muzzle_bridge_ShaderBuffer
 * Method:    unload
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_ShaderBuffer_unload
  (JNIEnv *, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_ShaderBuffer
 * Method:    resize
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_ShaderBuffer_resize
  (JNIEnv *, jobject, jlong);

/*
 * Class:     dev_pikostudios_muzzle_bridge_ShaderBuffer
 * Method:    upload
 * Signature: (Ljava/nio/ByteBuffer;JJ)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_ShaderBuffer_upload
  (JNIEnv *, jobject, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
