/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_pikostudios_muzzle_bridge_Applet */

#ifndef _Included_dev_pikostudios_muzzle_bridge_Applet
#define _Included_dev_pikostudios_muzzle_bridge_Applet
#ifdef __cplusplus
extern "C" {
#endif
#undef dev_pikostudios_muzzle_bridge_Applet_APPLET_FLAG_RESIZABLE
#define dev_pikostudios_muzzle_bridge_Applet_APPLET_FLAG_RESIZABLE 1L
#undef dev_pikostudios_muzzle_bridge_Applet_APPLET_FLAG_VSYNC
#define dev_pikostudios_muzzle_bridge_Applet_APPLET_FLAG_VSYNC 2L
#undef dev_pikostudios_muzzle_bridge_Applet_APPLET_FLAG_TRACK_DELTA_TIME
#define dev_pikostudios_muzzle_bridge_Applet_APPLET_FLAG_TRACK_DELTA_TIME 4L
/*
 * Class:     dev_pikostudios_muzzle_bridge_Applet
 * Method:    initialize
 * Signature: (Ljava/lang/String;III)Ldev/pikostudios/muzzle/bridge/Applet;
 */
JNIEXPORT jobject JNICALL Java_dev_pikostudios_muzzle_bridge_Applet_initialize
  (JNIEnv *, jclass, jstring, jint, jint, jint);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Applet
 * Method:    start
 * Signature: (Ldev/pikostudios/muzzle/bridge/Applet/DispatchCallback;)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Applet_start
  (JNIEnv *, jobject, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Applet
 * Method:    keepRunning
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_dev_pikostudios_muzzle_bridge_Applet_keepRunning
  (JNIEnv *, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Applet
 * Method:    terminate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Applet_terminate
  (JNIEnv *, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Applet
 * Method:    updateWindowTitle
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Applet_updateWindowTitle
  (JNIEnv *, jobject, jstring);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Applet
 * Method:    getWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dev_pikostudios_muzzle_bridge_Applet_getWidth
  (JNIEnv *, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Applet
 * Method:    getHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dev_pikostudios_muzzle_bridge_Applet_getHeight
  (JNIEnv *, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_Applet
 * Method:    getDeltaTime
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_dev_pikostudios_muzzle_bridge_Applet_getDeltaTime
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
