/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_pikostudios_muzzle_bridge_GraphicsPipeline */

#ifndef _Included_dev_pikostudios_muzzle_bridge_GraphicsPipeline
#define _Included_dev_pikostudios_muzzle_bridge_GraphicsPipeline
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_pikostudios_muzzle_bridge_GraphicsPipeline
 * Method:    create
 * Signature: (Ldev/pikostudios/muzzle/bridge/Shader;[IIIZI)Ldev/pikostudios/muzzle/bridge/GraphicsPipeline;
 */
JNIEXPORT jobject JNICALL Java_dev_pikostudios_muzzle_bridge_GraphicsPipeline_create
  (JNIEnv *, jclass, jobject, jintArray, jint, jint, jboolean, jint);

/*
 * Class:     dev_pikostudios_muzzle_bridge_GraphicsPipeline
 * Method:    clearDepthBuffer
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_GraphicsPipeline_clearDepthBuffer
  (JNIEnv *, jobject, jfloat);

/*
 * Class:     dev_pikostudios_muzzle_bridge_GraphicsPipeline
 * Method:    getFramebufferID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dev_pikostudios_muzzle_bridge_GraphicsPipeline_getFramebufferID
  (JNIEnv *, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_GraphicsPipeline
 * Method:    getFramebufferWidth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dev_pikostudios_muzzle_bridge_GraphicsPipeline_getFramebufferWidth
  (JNIEnv *, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_GraphicsPipeline
 * Method:    getFramebufferHeight
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dev_pikostudios_muzzle_bridge_GraphicsPipeline_getFramebufferHeight
  (JNIEnv *, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_GraphicsPipeline
 * Method:    getColorAttachmentsCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dev_pikostudios_muzzle_bridge_GraphicsPipeline_getColorAttachmentsCount
  (JNIEnv *, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_GraphicsPipeline
 * Method:    getColorAttachmentTexture
 * Signature: (I)Ldev/pikostudios/muzzle/bridge/Sprite;
 */
JNIEXPORT jobject JNICALL Java_dev_pikostudios_muzzle_bridge_GraphicsPipeline_getColorAttachmentTexture
  (JNIEnv *, jobject, jint);

/*
 * Class:     dev_pikostudios_muzzle_bridge_GraphicsPipeline
 * Method:    getColorAttachmentID
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dev_pikostudios_muzzle_bridge_GraphicsPipeline_getColorAttachmentID
  (JNIEnv *, jobject, jint);

/*
 * Class:     dev_pikostudios_muzzle_bridge_GraphicsPipeline
 * Method:    getDepthBufferTexture
 * Signature: ()Ldev/pikostudios/muzzle/bridge/Sprite;
 */
JNIEXPORT jobject JNICALL Java_dev_pikostudios_muzzle_bridge_GraphicsPipeline_getDepthBufferTexture
  (JNIEnv *, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_GraphicsPipeline
 * Method:    getDepthBufferID
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dev_pikostudios_muzzle_bridge_GraphicsPipeline_getDepthBufferID
  (JNIEnv *, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_GraphicsPipeline
 * Method:    unload
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_GraphicsPipeline_unload
  (JNIEnv *, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_GraphicsPipeline
 * Method:    _getDepthBufferType
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dev_pikostudios_muzzle_bridge_GraphicsPipeline__1getDepthBufferType
  (JNIEnv *, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_GraphicsPipeline
 * Method:    _getColorAttachmentFormat
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_dev_pikostudios_muzzle_bridge_GraphicsPipeline__1getColorAttachmentFormat
  (JNIEnv *, jobject, jint);

/*
 * Class:     dev_pikostudios_muzzle_bridge_GraphicsPipeline
 * Method:    _clearColorAttachments
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_GraphicsPipeline__1clearColorAttachments
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     dev_pikostudios_muzzle_bridge_GraphicsPipeline
 * Method:    _dispatch
 * Signature: (Ldev/pikostudios/muzzle/bridge/Applet;Ldev/pikostudios/muzzle/bridge/VertexBuffer;JJ)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_GraphicsPipeline__1dispatch
  (JNIEnv *, jobject, jobject, jobject, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
