/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_pikostudios_muzzle_bridge_Rectangle */

#ifndef _Included_dev_pikostudios_muzzle_bridge_Rectangle
#define _Included_dev_pikostudios_muzzle_bridge_Rectangle
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_pikostudios_muzzle_bridge_Rectangle
 * Method:    draw
 * Signature: (Ldev/pikostudios/muzzle/bridge/Applet;FFFFLdev/pikostudios/muzzle/bridge/Tint;)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_Rectangle_draw
  (JNIEnv *, jclass, jobject, jfloat, jfloat, jfloat, jfloat, jobject);

#ifdef __cplusplus
}
#endif
#endif
