/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_pikostudios_muzzle_bridge_ShaderPipeline */

#ifndef _Included_dev_pikostudios_muzzle_bridge_ShaderPipeline
#define _Included_dev_pikostudios_muzzle_bridge_ShaderPipeline
#ifdef __cplusplus
extern "C" {
#endif
#undef dev_pikostudios_muzzle_bridge_ShaderPipeline_PRIMITIVE_TYPE_TRIANGLE
#define dev_pikostudios_muzzle_bridge_ShaderPipeline_PRIMITIVE_TYPE_TRIANGLE 0L
#undef dev_pikostudios_muzzle_bridge_ShaderPipeline_PRIMITIVE_TYPE_TRIANGLE_STRIP
#define dev_pikostudios_muzzle_bridge_ShaderPipeline_PRIMITIVE_TYPE_TRIANGLE_STRIP 1L
#undef dev_pikostudios_muzzle_bridge_ShaderPipeline_PRIMITIVE_TYPE_POINT
#define dev_pikostudios_muzzle_bridge_ShaderPipeline_PRIMITIVE_TYPE_POINT 2L
/*
 * Class:     dev_pikostudios_muzzle_bridge_ShaderPipeline
 * Method:    create
 * Signature: (I[FLjava/lang/String;Z[Ldev/pikostudios/muzzle/bridge/ShaderPipeline/Attribute;Ljava/lang/String;ZLjava/lang/String;Z)Ldev/pikostudios/muzzle/bridge/ShaderPipeline;
 */
JNIEXPORT jobject JNICALL Java_dev_pikostudios_muzzle_bridge_ShaderPipeline_create
  (JNIEnv *, jclass, jint, jfloatArray, jstring, jboolean, jobjectArray, jstring, jboolean, jstring, jboolean);

/*
 * Class:     dev_pikostudios_muzzle_bridge_ShaderPipeline
 * Method:    draw
 * Signature: ([FII)V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_ShaderPipeline_draw
  (JNIEnv *, jobject, jfloatArray, jint, jint);

/*
 * Class:     dev_pikostudios_muzzle_bridge_ShaderPipeline
 * Method:    unload
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_ShaderPipeline_unload
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
