/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class dev_pikostudios_muzzle_bridge_VertexBuffer */

#ifndef _Included_dev_pikostudios_muzzle_bridge_VertexBuffer
#define _Included_dev_pikostudios_muzzle_bridge_VertexBuffer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     dev_pikostudios_muzzle_bridge_VertexBuffer
 * Method:    create
 * Signature: (I[Ldev/pikostudios/muzzle/bridge/VertexBuffer/AttributeDescriptor;)Ldev/pikostudios/muzzle/bridge/VertexBuffer;
 */
JNIEXPORT jobject JNICALL Java_dev_pikostudios_muzzle_bridge_VertexBuffer_create
  (JNIEnv *, jclass, jint, jobjectArray);

/*
 * Class:     dev_pikostudios_muzzle_bridge_VertexBuffer
 * Method:    getSize
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_dev_pikostudios_muzzle_bridge_VertexBuffer_getSize
  (JNIEnv *, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_VertexBuffer
 * Method:    getStride
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_dev_pikostudios_muzzle_bridge_VertexBuffer_getStride
  (JNIEnv *, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_VertexBuffer
 * Method:    getVAO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dev_pikostudios_muzzle_bridge_VertexBuffer_getVAO
  (JNIEnv *, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_VertexBuffer
 * Method:    getVBO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_dev_pikostudios_muzzle_bridge_VertexBuffer_getVBO
  (JNIEnv *, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_VertexBuffer
 * Method:    getTopologyType
 * Signature: ()Ldev/pikostudios/muzzle/bridge/VertexBuffer/TopologyType;
 */
JNIEXPORT jobject JNICALL Java_dev_pikostudios_muzzle_bridge_VertexBuffer_getTopologyType
  (JNIEnv *, jobject);

/*
 * Class:     dev_pikostudios_muzzle_bridge_VertexBuffer
 * Method:    unload
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_dev_pikostudios_muzzle_bridge_VertexBuffer_unload
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
