#ifndef MUZZLE_GPU_TEXTURE_H
#define MUZZLE_GPU_TEXTURE_H

// Sourced from https://docs.gl/gl4/glTexStorage2D
// 1-to-1 match with OpenGL texture internal formats
// These values represent how the texture data being copied is stored on the host
typedef enum
{
    GPU_TEXTURE_INTERNAL_FORMAT_R8 = 0,
    GPU_TEXTURE_INTERNAL_FORMAT_R8_SNORM,
    GPU_TEXTURE_INTERNAL_FORMAT_R16,
    GPU_TEXTURE_INTERNAL_FORMAT_R16_SNORM,
    GPU_TEXTURE_INTERNAL_FORMAT_RG8,
    GPU_TEXTURE_INTERNAL_FORMAT_RG8_SNORM,
    GPU_TEXTURE_INTERNAL_FORMAT_RG16,
    GPU_TEXTURE_INTERNAL_FORMAT_RG16_SNORM,
    GPU_TEXTURE_INTERNAL_FORMAT_R3_G3_B2,
    GPU_TEXTURE_INTERNAL_FORMAT_RGB4,
    GPU_TEXTURE_INTERNAL_FORMAT_RGB5,
    GPU_TEXTURE_INTERNAL_FORMAT_RGB8,
    GPU_TEXTURE_INTERNAL_FORMAT_RGB8_SNORM,
    GPU_TEXTURE_INTERNAL_FORMAT_RGB10,
    GPU_TEXTURE_INTERNAL_FORMAT_RGB12,
    GPU_TEXTURE_INTERNAL_FORMAT_RGB16_SNORM,
    GPU_TEXTURE_INTERNAL_FORMAT_RGBA2,
    GPU_TEXTURE_INTERNAL_FORMAT_RGBA4,
    GPU_TEXTURE_INTERNAL_FORMAT_RGB5_A1,
    GPU_TEXTURE_INTERNAL_FORMAT_RGBA8,
    GPU_TEXTURE_INTERNAL_FORMAT_RGBA8_SNORM,
    GPU_TEXTURE_INTERNAL_FORMAT_RGB10_A2,
    GPU_TEXTURE_INTERNAL_FORMAT_RGB10_A2UI,
    GPU_TEXTURE_INTERNAL_FORMAT_RGBA12,
    GPU_TEXTURE_INTERNAL_FORMAT_RGBA16,
    GPU_TEXTURE_INTERNAL_FORMAT_SRGB8,
    GPU_TEXTURE_INTERNAL_FORMAT_SRGB8_ALPHA8,
    GPU_TEXTURE_INTERNAL_FORMAT_R16F,
    GPU_TEXTURE_INTERNAL_FORMAT_RG16F,
    GPU_TEXTURE_INTERNAL_FORMAT_RGB16F,
    GPU_TEXTURE_INTERNAL_FORMAT_RGBA16F,
    GPU_TEXTURE_INTERNAL_FORMAT_R32F,
    GPU_TEXTURE_INTERNAL_FORMAT_RG32F,
    GPU_TEXTURE_INTERNAL_FORMAT_RGB32F,
    GPU_TEXTURE_INTERNAL_FORMAT_RGBA32F,
    GPU_TEXTURE_INTERNAL_FORMAT_R11F_G11F_B10F,
    GPU_TEXTURE_INTERNAL_FORMAT_RGB9_E5,
    GPU_TEXTURE_INTERNAL_FORMAT_R8I,
    GPU_TEXTURE_INTERNAL_FORMAT_R8UI,
    GPU_TEXTURE_INTERNAL_FORMAT_R16I,
    GPU_TEXTURE_INTERNAL_FORMAT_R16UI,
    GPU_TEXTURE_INTERNAL_FORMAT_R32I,
    GPU_TEXTURE_INTERNAL_FORMAT_R32UI,
    GPU_TEXTURE_INTERNAL_FORMAT_RG8I,
    GPU_TEXTURE_INTERNAL_FORMAT_RG8UI,
    GPU_TEXTURE_INTERNAL_FORMAT_RG16I,
    GPU_TEXTURE_INTERNAL_FORMAT_RG16UI,
    GPU_TEXTURE_INTERNAL_FORMAT_RG32I,
    GPU_TEXTURE_INTERNAL_FORMAT_RG32UI,
    GPU_TEXTURE_INTERNAL_FORMAT_RGB8I,
    GPU_TEXTURE_INTERNAL_FORMAT_RGB8UI,
    GPU_TEXTURE_INTERNAL_FORMAT_RGB16I,
    GPU_TEXTURE_INTERNAL_FORMAT_RGB16UI,
    GPU_TEXTURE_INTERNAL_FORMAT_RGB32I,
    GPU_TEXTURE_INTERNAL_FORMAT_RGB32UI,
} mz_gpu_texture_internal_format;

// Sourced form https://docs.gl/gl4/glTexSubImage2D
typedef enum
{
    GPU_TEXTURE_FORMAT_R,
    GPU_TEXTURE_FORMAT_RG,
    GPU_TEXTURE_FORMAT_RGB,
    GPU_TEXTURE_FORMAT_BGR,
    GPU_TEXTURE_FORMAT_RGBA,
    GPU_TEXTURE_FORMAT_BGRA,
    GPU_TEXTURE_FORMAT_DEPTH_COMPONENT,
    GPU_TEXTURE_FORMAT_STENCIL_INDEX,
} mz_gpu_texture_format;

// Sourced from https://docs.gl/gl4/glTexSubImage2D
typedef enum
{
    GPU_TEXTURE_DATA_TYPE_UNSIGNED_BYTE,
    GPU_TEXTURE_DATA_TYPE_BYTE,
    GPU_TEXTURE_DATA_TYPE_UNSIGNED_SHORT,
    GPU_TEXTURE_DATA_TYPE_SHORT,
    GPU_TEXTURE_DATA_TYPE_UNSIGNED_INT,
    GPU_TEXTURE_DATA_TYPE_INT,
    GPU_TEXTURE_DATA_TYPE_FLOAT,
} mz_gpu_texture_data_type;

// Sourced from https://docs.gl/gl4/glCreateTextures
typedef enum
{
    GPU_TEXTURE_TYPE_1D,
    GPU_TEXTURE_TYPE_1D_ARRAY,
    GPU_TEXTURE_TYPE_2D,
    GPU_TEXTURE_TYPE_2D_ARRAY,
    GPU_TEXTURE_TYPE_2D_MULTISAMPLE,
    GPU_TEXTURE_TYPE_2D_MULTISAMPLE_ARRAY,
    GPU_TEXTURE_TYPE_3D,
    GPU_TEXTURE_TYPE_RECTANGLE,
    GPU_TEXTURE_TYPE_CUBE_MAP,
    GPU_TEXTURE_TYPE_CUBE_MAP_ARRAY,
    GPU_TEXTURE_TYPE_BUFFER
} mz_gpu_texture_type;

#endif // MUZZLE_GPU_TEXTURE_H
